site_name: Documentation for the ML4DQM/DC code
nav:
    - Home: 'index.md'
    - dqmio:
        - README: 'dqmio/README.md'
        - harvest_nanodqmio_submit: 'dqmio/harvest_nanodqmio_submit.md'
        - harvest_nanodqmio_submitmultiple: 'dqmio/harvest_nanodqmio_submitmultiple.md'
        - harvest_nanodqmio_to_csv: 'dqmio/harvest_nanodqmio_to_csv.md'
        - harvest_nanodqmio_to_parquet: 'dqmio/harvest_nanodqmio_to_parquet.md'
        - harvest_nanodqmio_to_root: 'dqmio/harvest_nanodqmio_to_root.md'
        - copydastolocal:
            - README: 'dqmio/copydastolocal/README.md'
            - copy_das_to_local_file: 'dqmio/copydastolocal/copy_das_to_local_file.md'
            - copy_das_to_local_set: 'dqmio/copydastolocal/copy_das_to_local_set.md'
        - utils:
            - README: 'dqmio/utils/README.md'
            - print_dataset_files: 'dqmio/utils/print_dataset_files.md'
            - print_mes: 'dqmio/utils/print_mes.md'
    - omsapi:
        - README: 'omsapi/README.md'
        - get_oms_data: 'omsapi/get_oms_data.md'
        - omsapi: 'omsapi/omsapi.md'
        - urls: 'omsapi/urls.md'
    - run:
        - README: 'run/README.md'
    - runswan:
        - README: 'runswan/README.md'
    - src:
        - DataLoader: 'src/DataLoader.md'
        - HistStruct: 'src/HistStruct.md'
        - Model: 'src/Model.md'
        - ModelInterface: 'src/ModelInterface.md'
        - PlotStyleParser: 'src/PlotStyleParser.md'
        - classifiers:
            - AutoEncoder: 'src/classifiers/AutoEncoder.md'
            - HistogramClassifier: 'src/classifiers/HistogramClassifier.md'
            - LandauClassifier: 'src/classifiers/LandauClassifier.md'
            - MaxPullClassifier: 'src/classifiers/MaxPullClassifier.md'
            - MomentClassifier: 'src/classifiers/MomentClassifier.md'
            - NMFClassifier: 'src/classifiers/NMFClassifier.md'
            - PCAClassifier: 'src/classifiers/PCAClassifier.md'
            - TemplateBasedClassifier: 'src/classifiers/TemplateBasedClassifier.md'
        - cloudfitters:
            - CloudFitter: 'src/cloudfitters/CloudFitter.md'
            - ExponentialFitter: 'src/cloudfitters/ExponentialFitter.md'
            - GaussianKdeFitter: 'src/cloudfitters/GaussianKdeFitter.md'
            - HyperRectangleFitter: 'src/cloudfitters/HyperRectangleFitter.md'
            - IdentityFitter: 'src/cloudfitters/IdentityFitter.md'
            - LogNormalFitter: 'src/cloudfitters/LogNormalFitter.md'
            - PCAGaussianFitter: 'src/cloudfitters/PCAGaussianFitter.md'
            - PCAGaussianKdeFitter: 'src/cloudfitters/PCAGaussianKdeFitter.md'
            - SeminormalFitter: 'src/cloudfitters/SeminormalFitter.md'
    - tutorials:
        - autoencoder_1d: 'tutorials/autoencoder_1d.md'
        - autoencoder_iterative: 'tutorials/autoencoder_iterative.md'
        - generate_data: 'tutorials/generate_data.md'
        - global_combined_training: 'tutorials/global_combined_training.md'
        - maxpull: 'tutorials/maxpull.md'
        - nmf_1d: 'tutorials/nmf_1d.md'
        - nmf_2d: 'tutorials/nmf_2d.md'
        - plot_histograms: 'tutorials/plot_histograms.md'
        - plot_histograms_2d: 'tutorials/plot_histograms_2d.md'
        - plot_histograms_loop: 'tutorials/plot_histograms_loop.md'
        - read_and_write_data: 'tutorials/read_and_write_data.md'
    - utils:
        - README: 'utils/README.md'
        - autoencoder_utils: 'utils/autoencoder_utils.md'
        - clustering_utils: 'utils/clustering_utils.md'
        - csv_utils: 'utils/csv_utils.md'
        - dataframe_utils: 'utils/dataframe_utils.md'
        - generate_data_2d_utils: 'utils/generate_data_2d_utils.md'
        - generate_data_utils: 'utils/generate_data_utils.md'
        - hist_utils: 'utils/hist_utils.md'
        - json_utils: 'utils/json_utils.md'
        - mask_utils: 'utils/mask_utils.md'
        - plot_utils: 'utils/plot_utils.md'
        - refruns_utils: 'utils/refruns_utils.md'
